app = "thebestbot"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  TELEGRAM_BOT_TOKEN = "7722007216:AAFdZs8B9ElrsQkBBeiM1CCsa_xH-JLB05Y"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
